import React, { useState, FormEvent } from 'react';
import Modal from './Modal';
import Input from './Input';
import Select from './Select';
import Button from './Button';
import { CostEstimatorData } from '../services/geminiService';

interface DeploymentCostEstimatorModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSubmit: (data: CostEstimatorData) => void;
    isLoading: boolean;
    result: string;
}

const DeploymentCostEstimatorModal: React.FC<DeploymentCostEstimatorModalProps> = ({
    isOpen,
    onClose,
    onSubmit,
    isLoading,
    result,
}) => {
    const [formData, setFormData] = useState<CostEstimatorData>({
        numUsers: '50',
        entriesPerUser: '1',
        summaryGenerations: '10',
        cloudProvider: 'GCP',
        databaseType: 'Managed SQL',
        redundancy: 'Single Region',
    });

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value as any }));
    };

    const handleSubmit = (e: FormEvent) => {
        e.preventDefault();
        onSubmit(formData);
    };

    return (
        <Modal isOpen={isOpen} onClose={onClose} title="Deployment Cost Estimator">
            <p className="text-sm text-slate-600 mb-4">
                Provide details about your expected usage to get a rough monthly cost estimate for deploying this application. This is powered by Gemini.
            </p>
            <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <Input
                        label="Number of Users"
                        id="numUsers"
                        name="numUsers"
                        type="number"
                        value={formData.numUsers}
                        onChange={handleChange}
                        required
                        min="1"
                    />
                    <Input
                        label="Avg Daily Entries / User"
                        id="entriesPerUser"
                        name="entriesPerUser"
                        type="number"
                        value={formData.entriesPerUser}
                        onChange={handleChange}
                        required
                        min="1"
                    />
                </div>
                <Input
                    label="AI Summaries / Month"
                    id="summaryGenerations"
                    name="summaryGenerations"
                    type="number"
                    value={formData.summaryGenerations}
                    onChange={handleChange}
                    required
                    min="0"
                />
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <Select label="Cloud Provider" id="cloudProvider" name="cloudProvider" value={formData.cloudProvider} onChange={handleChange}>
                        <option>GCP</option>
                        <option>AWS</option>
                        <option>Azure</option>
                    </Select>
                    <Select label="Database Type" id="databaseType" name="databaseType" value={formData.databaseType} onChange={handleChange}>
                        <option>Managed SQL</option>
                        <option>NoSQL</option>
                        <option>Self-hosted</option>
                    </Select>
                </div>
                <Select label="Redundancy" id="redundancy" name="redundancy" value={formData.redundancy} onChange={handleChange}>
                    <option>Single Region</option>
                    <option>Multi-Region</option>
                </Select>

                <div className="pt-4 flex justify-end">
                    <Button type="submit" isLoading={isLoading}>
                        Calculate Estimated Cost
                    </Button>
                </div>
            </form>
            {result && !isLoading && (
                 <div className="mt-6 p-4 bg-slate-50 border border-slate-200 rounded-lg">
                    <h4 className="font-semibold text-slate-800 mb-2">Estimation Result:</h4>
                    <div className="prose prose-sm max-w-none" dangerouslySetInnerHTML={{ __html: result.replace(/\n/g, '<br />') }}></div>
                     <p className="text-xs text-slate-400 mt-4 italic">
                        Disclaimer: This is a high-level estimate generated by an AI model. Actual costs can vary based on usage, region, and specific configurations.
                    </p>
                 </div>
            )}
        </Modal>
    );
};

export default DeploymentCostEstimatorModal;
